### PR TITLE
Fix error when context-menu is unavailable

### PR DESCRIPTION
**Pull request by Jaskaranbir**
Prevents crash-errors in the console if the context-menus extension is not installed. Better solution is still to add an option to disable context-menu, but we should have some default check regardless.

### CODE REVIEW

**Comment by msalihaltun** [comment]
Hello @Jaskaranbir, thank you for your interest in this extension and the PR.

This probably will solve the errors in console, but am not sure we want that to happen. At this point, this extension only functions with `context-menus` enabled. I would consider it an error, in context of this extension, if `context-menus` is not enabled. So it makes sense to me that the extension would fail, and fail loudly to tell you what is wrong. 

The only functionality not dependent on `context-menus` is reconnecting edges. If that is the only thing you want to do maybe that sort of option could be considered -though I would still argue it doesn't fit the purposes of this extension-, but if you are thinking about programatically changing the data fields etc to introduce anchors, then you can do that with Cytoscape alone just as well.

We can discuss further about the issues above. Also just FYI, we do development of extensions in `unstable` branch in general. I know this is not well documented, so sorry about that.

**Comment by Jaskaranbir** [comment]
Thanks for the insight @msalihaltun. I do think that this extension still has immense value even without context-menus. The "create anchor by dragging" and reconnecting-edges were two important features for our project, and it would have made things much more challenging given our limited timeframe for project and lack of prior Cytoscape

**Comment by Jaskaranbir** [comment]
Accidentally closed PR.

**Comment by msalihaltun** [comment]
Creating anchors by drag is only available when you have at least one anchor already on the edge, since we can't determine whether user wants to create bend or control points otherwise (an edge can't have both types of anchors). You can confirm this in the demo as well (one of the edges has a bend point that is "pre-loaded" in the demo so you can create anchors through drag on it but this won't be the case in general). So in this way, it is not actually possible to have anchors without using `context-menus` in the first place.

Also even if we accepted this it wouldn't be released for a while at this point since we just recently went through a cycle of releases.

My suggestion to you at this point would be to create a fork of this project and implement your change there for your project specifically and use the extension from that version.

**Comment by Jaskaranbir** [comment]
We did add an anchor by default in middle of the edge, and I think that sorta implementation would be fair.

But it does look like the goal is to keep the context-menu coupling, atleast for near-future. So I'll close this PR for now, feel free to use this if there's change in plans in future and the implementation is still viable.

**Pull request closed without merging**
