### PR TITLE
modifications:

### PR DESCRIPTION
**Pull request by leolumicrosoft**
- stick anchor point to 0 45 or 90 angle refer to prev or next anchor (one small defect from previous implementation is fixed)
- add option to keep anchor point size the same no matter zoom level
- add option to disable removing anchor because of it is in a mid of line
-add option to disable drag edge to add bend point

### CODE REVIEW

**Comment by canbax** [comment]
I don't see the effect of `stickyAnchorTolerence` I set it -1 and 20. I don't see any change in behaviour

**Comment by canbax** [comment]
Hi @leolumicrosoft Based on your pull request we added 2 new options in https://github.com/iVis-at-Bilkent/cytoscape.js-edge-editing/commit/d2bcd82a3781c5aac5c87399b6e5c7609593a422 

For 
> -add option to disable drag edge to add bend point
we already have option `enableCreateAnchorOnDrag`

For the others, we think it might complicate code too much since we also plan to add support https://github.com/iVis-at-Bilkent/cytoscape.js-edge-editing/issues/17

**Comment by hasanbalci** [comment]
I'm closing this PR, thanks @leolumicrosoft for your contributions.

**Comment by mike-kelly** [comment]
I am also keen to have the 'stick anchor point to 0 45 or 90 angle refer to prev or next anchor' feature, which I think is different from #17

It could also be described as a 'snap-to-grid' type functionality.

**Pull request closed without merging**
